### ISSUE TITLE
Add the hotel tables, you can open Hotel.txt to see.

### ISSUE THREAD

**Issue by FrankChe** [camouflage/Database#3]

**Comment by camouflage** [comment]
I have moved the info to file attrs.
REMEMBER: git pull BEFORE any modification.

**Comment by FrankChe** [comment]
Where is git pull?

**Comment by camouflage** [comment]
Type in command line.

**Comment by YuMeiLau** [comment]
@FrankChe 不用命令行也可以 可以用pull request那个选项 然后自己merge一下…

**Comment by YuMeiLau** [comment]
@camouflage 如果在本地git pull也只能用命令行是吧…
