### ISSUE TITLE
雨薇提提意见，看看有什么改的地方

### ISSUE THREAD

**Issue by FrankChe** [camouflage/Database#4]

**Comment by YuMeiLau** [comment]
不错啊。
可以考虑细致点吧。
1. 预订信息，包括通过Airbnb / Agoda这样的网站预订的客户。感觉这是很大一块。
2. 房间信息，是否清洁过，东西是否齐全，诸如此类。

**Comment by FrankChe** [comment]
我们的目标就是正好满足所有要求就好～
